app-engine/frontend/src/locale/en_US.json
app-engine/frontend/src/locale/zh_CN.json

[frontend] 优化前端报错提示信息

---

app-builder/jane/jober/sql/jade/02_appbuilder_create.sql
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AippRunTimeServiceImpl.java
app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/converter/ConvertorUtils.java
app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/entity/MetaInstance.java
app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/po/MetaInstancePo.java

处理任务兼容插件在表单场景的问题，主要为类型转换的错误。在之前任务插件中，该问题也存在，但是被忽略了。

[app-builder] 处理任务兼容插件在表单场景的问题

---

app-engine/frontend/src/pages/components/text-editor.tsx

修改tinymce插件设置language、skin、content css的路径

[frontend] 修复发布公告富文本编辑器工具栏没显示问题

---

app-engine/frontend/src/pages/components/text-editor.tsx

[frontend] 修复白屏的问题

---

.github/workflows/app-platform-java-compile.yml

[app-platform] 添加github action文件，范围包括app-builder中除了fel的python目录，app-engine中除了frontend目录，app-image，app-knowledge，carver，common以及store目录

[app-platform] 添加 app-platform 的 github action 文件

---

common/plugins/appengine-oms-adapter/src/main/resources/api/common.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-aipp.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-appBuilder.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-eval.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-metrics.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-northApi.json
common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-store.json
common/plugins/appengine-oms-adapter/src/main/resources/menu/preset_menu_data.json
common/plugins/appengine-oms-adapter/src/main/resources/role/preset_role.json
common/plugins/appengine-oms-adapter/src/main/resources/role/preset_role_i18n.json

新增开源社区用户角色

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderAppServiceImpl.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/AppImExportUtil.java
app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderAppServiceImplTest.java
app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/impl/AppTemplateServiceImplTest.java
app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/util/AppImExportUtilTest.java

[app-builder] 头像上传url前缀配置化

---

app-builder/fel/java/pom.xml
app-builder/jane/dynamic-form-genericable/pom.xml
app-builder/plugins/plugins-show-case-parent/agent-test/pom.xml
app-builder/plugins/plugins-show-case-parent/fortune-telling/pom.xml
app-builder/plugins/plugins-show-case-parent/wenjie-data/pom.xml
app-builder/waterflow/java/pom.xml
app-builder/waterflow/java/waterflow-dependency/pom.xml
app-engine/plugins/app-metrics/pom.xml
common/components/ui-word-globalizer/pom.xml
common/dependency/pom.xml
pom.xml

修复启动报错：io.opentelemetry.sdk.trace.export.SpanExporter类找不到

[app-builder] 修复启动报错问题

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/condition/FormQueryCondition.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderFormServiceImpl.java
app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AppBuilderFormMapper.xml
app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderFormServiceImplTest.java

[app-builder] 智能表单查询接口不返回内置表单

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/CacheUtils.java

[app-builder] 修复已发布应用对话失败问题

---

app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_en.json
app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_zh.json

[app-builder] 增加基础节点：问题优化、问题分类、文本提取

---

app-builder/plugins/aipp-custom-model-center/src/main/resources/sql/aipp_custom_model_center.sql

[app-builder] 模型表添加唯一约束

---

app-engine/frontend/src/index.tsx
app-engine/frontend/src/pages/chatPreview/components/history-chat/index.tsx
app-engine/frontend/src/pages/chatPreview/components/send-editor/common/config.ts
app-engine/frontend/src/pages/chatPreview/components/send-editor/components/file-list.tsx
app-engine/frontend/src/pages/chatPreview/index.tsx
app-engine/frontend/src/pages/chatPreview/styles/chat-details.scss

1、对话历史记录点击继续聊天没有获取点赞状态问题修复
2、对话中返回页面流式继续输出问题修复
3、文件对话类型去掉doc和xls格式

[forntend] 修复应用聊天对话失败问题

---

app-engine/frontend/src/app.tsx
app-engine/frontend/src/pages/appDetail/overview/style.scoped.scss

[frontend] 国际化字段取值修改

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/condition/AppQueryCondition.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/controller/AppBuilderAppController.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/northbound/AppBuilderAppServiceAdapterImpl.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/AppBuilderAppService.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderAppServiceImpl.java
app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AppBuilderAppMapper.xml
app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderAppServiceImplTest.java
app-builder/jane/services/aipp-genericable/src/main/java/modelengine/fit/jober/aipp/genericable/adapter/AppBuilderAppServiceAdapter.java
app-builder/plugins/aipp-northbound/src/main/java/modelengine/fit/jade/aipp/northbound/controller/AppBuilderAppController.java

[app-builder] 支持应用的多用户隔离

---

app-builder/plugins/aipp-northbound/src/test/java/modelengine/fit/jade/aipp/northbound/controller/AppBuilderAppControllerTest.java

[app-builder] 修复aipp-northbound单测

---

app-builder/plugins/plugins-show-case-parent/aito-data/pom.xml

[app-builder] 移动 aito 插件到指定目录

---

app-engine/frontend/src/components/plugin-card/index.tsx
app-engine/frontend/src/pages/addFlow/components/tool-table.tsx
app-engine/frontend/src/pages/addFlow/styles/tool-modal.scss
app-engine/frontend/src/pages/addFlow/styles/tool-table.scss
app-engine/frontend/src/pages/plugin/market.tsx

1、修复接口返回字段缺少导致插件列表名称显示失败问题
2、修复编排页面插件选择失败问题

[frontend] 插件列表问题修复

---

doc/Java插件开发指导.md
doc/Python插件开发指导.md

插件编译生成元数据结构升级，因此需要同步升级插件开发指导文档

[plugin] 插件开发文档适配最新插件结构

---

app-engine/frontend/src/components/appCard/index.tsx
app-engine/frontend/src/components/file-upload/index.scoped.scss
app-engine/frontend/src/components/file-upload/index.tsx
app-engine/frontend/src/pages/appDev/components/copy-app.tsx

[frontend] 添加应用复制入口按钮

---

app-engine/frontend/src/locale/en_US.json
app-engine/frontend/src/locale/zh_CN.json

[app-builder] 增加elsa-tool-bar的相关翻译

[app-builder] 增加elsa-tool-bar的相关翻译

---

app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/OpenAiModel.java
app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/entity/chat/OpenAiChatCompletionResponse.java
app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/entity/chat/OpenAiChatMessage.java
app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/enums/ModelProcessingState.java

deepseek api通过reasoning_content返回推理内容，进行相关适配

[app-builder] 适配模型对话接口reasoning_content

---

app-builder/plugins/aipp-parallel-tool/pom.xml
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequest.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/Argument.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/Config.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/ToolCall.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/service/ParallelToolService.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/service/impl/ParallelToolServiceImpl.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/AippInstanceStatus.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/TaskExecutor.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/impl/AippInstanceStatusImpl.java
app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/impl/DefaultTaskExecutor.java
app-builder/plugins/aipp-parallel-tool/src/test/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequestTest.java
app-builder/plugins/pom.xml

1. 增加并行执行工具的插件，提供一次并行执行多个工具的能力，后续应用编排中可以使用。

[app-factory] 增加并行执行工具的插件

---

app-engine/frontend/src/pages/chatPreview/components/send-editor/common/config.ts
app-engine/frontend/src/pages/chatPreview/components/send-editor/components/file-list.tsx

[frontend] 文件对话上传添加docx和xlsx类型

---

app-knowledge/plugins/knowledge-manager/src/main/resources/sql/aipp_user_knowledge.sql

[app-platform] 知识库表创建index语句修改

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/AppImExportUtil.java

兼容旧数据，规避应用导出时config property找不到对应form property时报错

[app-builder] 应用导出旧数据报错修复

---

app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImpl.java
app-knowledge/plugins/knowledge-manager/src/main/resources/sql/aipp_user_knowledge.sql

1. 由于加解密，修改表中api Key字段配置
2. 修改知识库工具代码api key处理逻辑

知识库apiKey处理逻辑修改

---

README.md

增加 README 文件的 ELSA 编译产物链接，用于本地的前端启动

[app-builder] 增加 README 文件的 ELSA 编译产物链接

---

shell/sql_build.sh

[app-builder] 并行节点数据库语句拷贝

---

.github/workflows/app-platform-java-compile.yml

- Extend CI triggers to include develop branch for:
- push events
- pull_request events
- Maintain existing path filters and other configurations

[app-builder] ci: add develop branch trigger

---

app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/KnowledgeControllerTest.java
app-knowledge/plugins/qianfan-knowledge/src/main/java/modelengine/jade/knowledge/entity/QianfanKnowledgeEntity.java
app-knowledge/plugins/qianfan-knowledge/src/main/java/modelengine/jade/knowledge/entity/QianfanKnowledgeListEntity.java

1. add "@JsonIgnoreProperties" annotation to ingore unused key in Qianfan interface response
2. add knowledgeController class test case

adapt to changes in Qianfan interface response 

---

app-engine/frontend/src/pages/addFlow/components/elsa-stage.tsx

1. remove redundant elsa function calls in frontend code.

fix frontend bug which set knowledge groupId as empty string

---

app-engine/frontend/package.json

请删除不适用的选项 / Please delete options that are not relevant
- 
- 
- 
1. 
2. 
3. 
---

[frontend] fix frontend build error

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/domains/appversion/publish/StorePublisher.java

**Issue 链接 / Issue Link:** https://github.com/ModelEngine-Group/app-platform/issues/234
1. 发布应用或者工具流时，针对app本身有 uniqueName 的场景下，也进行 groupName 等字段的填充。以防止 groupName 等字段的缺失，导致工具的数据插入数据库失败，进而导致发布失败。
When publishing an application or tool flow, if the app itself has a uniqueName, fill in fields such as groupName to prevent deletion of fields such as groupName, which may cause the tool to fail to insert data into the database and then cause publishing failure.
1. 创建工具流并发布 / Create a water flow and publish it
2. 将已发布的工具流再次发布 / Republish the water flow
3. 再次发布可以成功 / Republishing can be successful
**文档和兼容性 / …

[appBuilder] 修复工具流无法多次发布的问题

---

app-engine/frontend/src/pages/configForm/configUi/components/inspiration-list.tsx

**Issue 链接 / Issue Link:** #239
- 创意灵感组件中handleDeleteIns方法传参有误，修改传参
The parameter passed to the handleDeleteIns method in the inspiration-list component is incorrect, modify the argument.
1. 在应用开发中创建或进入任意应用 / enter an app
2. 添加创意灵感 / add an inspiration
3. 删除添加的创意灵感 / succeed to delete the inspiration
---

[frontend] bugfix: cannot remove inspiration

---

app-engine/frontend/src/pages/chatPreview/index.tsx

**Issue 链接 / Issue Link:** #248 
- 修改chatPreview组件中chatStrInit方法对于enableLog为false的最终信息的处理 / Modify the chatStrInit method in the chatPreview component to handle the final message correctly when enableLog is set to false.
1. 创建应用，设置结束节点引用非模型节点输出
2. 在调试界面进行对话，观察到应用输出模型节点内容，并且不会变成结束节点所配置内容
---

[frontend] bugfix: enableLog configuration not taking effect at end node

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/domains/appversion/AppVersion.java

**Issue 链接 / Issue Link:** #276 
- 在应用autoChatOnUpload配置为true时，用户问题Question字段允许为空，因此启动对话时应将问题内容的最小长度校验调整为 0。
When the application's autoChatOnUpload configuration is set to true, the user's Question field is allowed to be empty. Therefore, the minimum length validation for the question should be set to 0 when initiating a conversation.
1. 创建应用
Create an app.
2. 在数据库修改该应用的autoChatOnUpload配置项为true
Set the autoChatOnUpload configuration to true in the database.
3. 在应用中上传文件开始对话，显示对话启动正常
Upload a file to trigger the conversation successfully.
---
**审查者注意事项 / Reviewer …

[app-builder] fix: set minimum question length to 0 in validation

---

app-engine/frontend/src/pages/chatPreview/index.tsx

**Issue 链接 / Issue Link:** #281
在首次对话或者新对话时，刷新页面不会出现"停止对话"按钮。原因是当前只在对话完成后才在前端缓存存放 chatId，而"停止对话"按钮出现的条件之一是缓存里的 chatId 存在。当前在对话 READY 后也设置chatId，保证首次会话过程时也有chatId
When you first start a new conversation, the "Stop Conversation" button will not appear when you refresh the page. The reason is that currently the chat is only stored in the hard disk storage or chatId after the conversation is completed, and one of the conditions for the "Stop Conversation" button to appear is that the chatId exists in the hard disk. Currently, the chatId is also set after the conversation is READY, ensuring that there is also a chatId during the first conversation process.
1. 创建应用，进入编排页，问个复杂问题，并刷新页面，看看有没有“停止对话”按钮 / Create an application, enter the orchestration page, ask a complex question, and refresh the …

[appBuilder] 在对话 READY 后也设置chatId

---

store/plugins/store-tool-uploader/src/main/java/modelengine/jade/store/tool/upload/utils/FormatFileUtils.java

**Issue 链接 / Issue Link:** https://github.com/ModelEngine-Group/app-platform/issues/301
当前插件的version值为标准数字没有SNAPSHOT时，上传的插件部署失败，会导致部署环境出现进程的部署线程死锁，后续正常插件也无法正常部署。 / When the version value of the current plug-in is a standard number without a SNAPSHOT, the uploaded plug-in deployment fails, causing the deployment thread of the process in the deployment environment to deadlock, and subsequent normal plug-ins cannot be deployed normally.
- 更新插件上传后插件扩展名的格式 /  Update the format of the plugin extension after the plugin is uploaded
1. 将之前上传出错的插件重新上传部署，插件部署不再失败  / Re-upload and deploy the previously uploaded plugin with errors, and the plugin deployment will no longer fail. …

[store] Fix the problem of plugin deployment failure caused by plugin version

---

app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_en.json
app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_zh.json

**Issue 链接 / Issue Link:** #25 
去除菜单栏中人工表单选项，归一表单
- 去除菜单栏中人工表单选项，归一表单
1. 菜单栏中只剩下表单

[frontend] Remove "Manual Check Form" item from the menu.

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/domains/appversion/AppVersion.java
app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/AppImExportUtil.java

**Issue 链接 / Issue Link:** #298 
- 在导入应用配置时对应用属性进行重置
reset attributes when importing an application
1. 创建一个应用，发布，导出该应用
Create an application, publish it, and export the app
2. 导入该应用
Import the application
3. 再次发布，发布成功
Publish it again and success
---

[app-builder] bugfix: reset app attributes when importing an app

---

store/plugins/store-repository-postgresql/src/main/resources/mapper/AppMapper.xml
store/plugins/store-repository-postgresql/src/test/java/modelengine/jade/store/repository/pgsql/integration/AppIntegrationTest.java
store/plugins/store-repository-postgresql/src/test/java/modelengine/jade/store/repository/pgsql/mapper/AppMapperTest.java
store/plugins/store-repository-postgresql/src/test/resources/sql/insert/app.sql

**Issue 链接 / Issue Link:** #303 
- 查询发布应用时根据creator进行排序，将creator为system的应用排在前
When querying published apps, sort by creator and prioritize apps created by "system".
1. 点击应用市场，发现system创建的应用在最前
System-created apps are listed at the top when entering the app market.
---

[app-builder] prioritize apps created by system in query results

---

app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/domains/appversion/ToolSchemaBuilder.java

Correct wrong app id assignment during publishing.
- Correct wrong app id assignment during publishing.
After publishing the application, verify that the aippId in the schema information of the corresponding store_tool table in the database is correct.
1. Publish an application.
2. Verify the aippId in the schema information of the store_tool table in the database.
---

[app-builder] correct wrong app id assignment during publishing

---

app-engine/frontend/src/locale/en_US.json
app-engine/frontend/src/locale/zh_CN.json
app-engine/frontend/src/pages/appDetail/overview/apiDocument.tsx
app-engine/frontend/src/pages/appDetail/overview/common/config.ts
app-engine/frontend/src/pages/appDetail/overview/styles/api.scss

**Issue 链接 / Issue Link:** #350 
北向接口文档增加国际化能力
- 北向接口文档增加国际化能力
1. x86启动环境
2. 切换语言环境为英文
3. 可以看到英文版的北向接口文档
---

[frontend] 北向接口文档增加国际化能力

---

app-builder/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/McpUtils.java

Compatible with more MCP servers.
- use the path as sse endpoint.
The LLM node successfully established dialogue via MCP server.
1. Create a application.
2. Config the mcp server in LLM node.
3. Debug the application.
---

[app-builder] mcp server compatible

---

README.md

**Issue 链接 / Issue Link:** #334 
The original script's syntax did not conform to the psql standard, causing the database to fail to initialize properly. Therefore, it was necessary to modify the script
**The main change was replacing the original 'CREATE OR REPLACE TRIGGER' with 'DROP TRIGGER IF EXISTS' followed by 'CREATE TRIGGER'.**
1. After executing the script, the database can be initialized properly.
---

Specify the PostgreSQL version number

---

frontend/src/pages/chatPreview/utils/marked-process.ts

修复应用对话内容大于小于号展示问题
- 应用对话时，xss防护配置修改不对html进行转义
1. 部署ModelEngine
2. 与应用对话，要求生成代码片段
3. 代码里的> <显示正常
---

[app-platform] 修复应用对话内容大于小于号展示问题

---

app-builder/plugins/aipp-http-call/src/test/java/modelengine/fit/jade/aipp/http/call/AippHttpCallServiceTest.java

修复报错测试用例
- 修复报错测试用例
1. 重新编译整个项目，编译通过
---

[app-platform] Fix failed tests.

---

.github/workflows/app-platform-java-compile.yml

此前1.1.x和1.2.x分支的action触发条件未带有自身分支，导致pr无法触发trigger。此变更修复该问题
- github action中增加对应的触发分支
1. 提交到对应目标分支的PR，触发测试
---

[app-platform] Add action trigger branches.

---

app-builder/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/domains/appversion/AppVersion.java

**Issue 链接 / Issue Link:** #386 
- 创建新应用时重置unique name和path
- 
- 
1. 创建应用，发布应用两次
2. 复制该应用
3. 删除复制的应用
4. 原应用存在，并且可以发布
---

[app-builder] bugfix: original app vanished after deleting the copy

---

frontend/src/locale/en_US.json
frontend/src/locale/zh_CN.json

修复代码节点说明错误问题
- 修复代码节点说明错误问题
1. 启动ModelEngine
2. 查看代码节点说明
3. 说明正常
---

修复代码节点说明错误问题

---

README.md

https://github.com/ModelEngine-Group/app-platform/issues/320
之前的写法路径分隔符使用”\\“，但在github上解析url分隔符是'/'。
修改了分隔符
在本地仓库上可以正常显示图片。
---

针对README中图片无法正常显示的修改

---

frontend/src/pages/addFlow/components/flow-test.tsx

**Issue 链接 / Issue Link:** #408 
- 在工作流调试时保持chat id，刷新页面或重新打开页面后视为一个新的对话
1. 在应用工作流调试时打开多轮对话开关
2. 进行多轮对话，验证大模型节点可以获取前几轮对话的内容
---

[frontend] add chat id when debugging waterflow

---

README.md
docker/dev-app-builder.sh

**Issue 链接 / Issue Link:** #437
- 增加本地容器化快速一键部署测试的脚本
- 添加 README 文档说明
1. 根据 README 文档快速开发测试章节测试
---

[app-builder] task: quick develop app-builder

---

frontend/src/pages/addFlow/config.ts

**Issue 链接 / Issue Link:** #429 
使得问题优化节点可以获取已有大模型列表
- 给问题优化节点添加大模型端点配置
1. 搭建工作流
2. 使用问题优化节点，可以获取到大模型列表

问题优化节点添加大模型访问端点
